spring.datasource.url=jdbc:postgresql://localhost:5432/backend_avito
spring.datasource.username=admin
spring.datasource.password=admin_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
upload.path=uploads
