--liquibase formatted sql

--changeset graduate-work:2
CREATE TABLE ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    description VARCHAR(1000),
    image VARCHAR(255),
    author_id BIGINT NOT NULL
);
