--liquibase formatted sql

--changeset graduate-work:3
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    created_at BIGINT NOT NULL,
    ad_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL
);
